import { cn, getScoreColor } from '@/lib/utils';
import { useAppStore } from '@/stores/app-store';
import { useMemo, useState } from 'react';
import { FileText, Download, Search, CheckCircle2, Clock, AlertTriangle, BarChart3, Shield } from 'lucide-react';

interface ReportEntry {
  id: string;
  title: string;
  date: string;
  score: number;
  violations: number;
  status: 'final' | 'draft';
  inspector: string;
}

export function ReportsView() {
  const { inspections, violations, facilities } = useAppStore();
  const [search, setSearch] = useState('');

  const reports = useMemo<ReportEntry[]>(() => {
    if (inspections.length === 0) return [];
    return inspections
      .slice()
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      .map((insp) => ({
        id: insp.id,
        title: `${insp.facility} — ${insp.type}`,
        date: insp.date,
        score: insp.score,
        violations: insp.violations_found,
        status: insp.status === 'completed' ? 'final' : 'draft',
        inspector: insp.inspector,
      }));
  }, [inspections]);

  const filtered = useMemo(() =>
    reports.filter((r) => r.title.toLowerCase().includes(search.toLowerCase())),
    [reports, search],
  );

  // Summary stats
  const totalInspections = inspections.length;
  const avgScore = facilities.length > 0
    ? Math.round(facilities.reduce((s, f) => s + f.score, 0) / facilities.length)
    : inspections.length > 0
    ? Math.round(inspections.reduce((s, i) => s + i.score, 0) / inspections.length)
    : 0;
  const totalViolations = violations.length;
  const resolvedViolations = violations.filter((v) => v.status === 'completed').length;

  const handleDownload = (report: ReportEntry) => {
    const lines = [
      `COMPLIANCE INSPECTION REPORT`,
      `================================`,
      `Title: ${report.title}`,
      `Date: ${report.date}`,
      `Inspector: ${report.inspector}`,
      `Compliance Score: ${report.score}%`,
      `Violations Found: ${report.violations}`,
      `Status: ${report.status.toUpperCase()}`,
      ``,
      `Generated by ComplianceSnap — ${new Date().toLocaleString()}`,
    ].join('\n');

    const blob = new Blob([lines], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-full flex-col">
      <div className="bg-bg-surface px-4 pb-4 pt-12">
        <h1 className="snap-heading-bold text-2xl text-text-primary">Reports</h1>

        {/* Summary stats */}
        <div className="mt-3 grid grid-cols-4 gap-2">
          {[
            { label: 'Inspections', value: totalInspections, icon: Shield, color: 'text-info' },
            { label: 'Avg Score', value: avgScore ? `${avgScore}%` : '—', icon: BarChart3, color: getScoreColor(avgScore) },
            { label: 'Violations', value: totalViolations, icon: AlertTriangle, color: 'text-severity-major' },
            { label: 'Resolved', value: resolvedViolations, icon: CheckCircle2, color: 'text-compliant' },
          ].map((s) => (
            <div key={s.label} className="rounded-xl bg-bg-card p-2 text-center">
              <s.icon className={cn('mx-auto h-4 w-4', s.color)} />
              <div className={cn('mt-1 text-sm font-bold', s.color)}>{s.value}</div>
              <div className="text-[9px] text-text-secondary">{s.label}</div>
            </div>
          ))}
        </div>

        <div className="mt-3 relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-secondary" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search reports..."
            className="h-10 w-full rounded-xl bg-bg-card pl-10 pr-3 text-sm text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-2 focus:ring-safety-yellow/50"
          />
        </div>
      </div>

      <div className="flex-1 overflow-auto px-4 pb-4 space-y-3">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <FileText className="mb-3 h-10 w-10 text-text-secondary" />
            <h2 className="text-sm font-medium text-text-primary">
              {reports.length === 0 ? 'No reports yet' : 'No reports match your search'}
            </h2>
            <p className="mt-1 text-xs text-text-secondary">
              {reports.length === 0
                ? 'Complete an inspection to generate a report.'
                : 'Try a different search term.'}
            </p>
          </div>
        ) : (
          filtered.map((r) => (
            <div key={r.id} className="rounded-xl bg-bg-card p-4">
              <div className="flex items-start gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-bg-surface">
                  <FileText className="h-5 w-5 text-text-secondary" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <div className="text-sm font-medium text-text-primary truncate">{r.title}</div>
                    <span className={cn(
                      'flex shrink-0 items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium',
                      r.status === 'final' ? 'bg-compliant-bg text-compliant' : 'bg-border-default/30 text-text-secondary',
                    )}>
                      {r.status === 'final' ? <CheckCircle2 className="h-3 w-3" /> : <Clock className="h-3 w-3" />}
                      {r.status === 'final' ? 'Final' : 'Draft'}
                    </span>
                  </div>
                  <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-text-secondary">
                    <span>{r.date}</span>
                    <span className={cn('font-medium', getScoreColor(r.score))}>{r.score}%</span>
                    {r.violations > 0 && (
                      <span className="flex items-center gap-0.5 text-severity-major">
                        <AlertTriangle className="h-3 w-3" />{r.violations}
                      </span>
                    )}
                    <span>{r.inspector}</span>
                  </div>
                </div>
              </div>
              <div className="mt-3 border-t border-border-default pt-3">
                <button
                  onClick={() => handleDownload(r)}
                  className="flex w-full items-center justify-center gap-1.5 rounded-lg bg-bg-surface py-2 text-xs text-text-secondary hover:bg-bg-card"
                >
                  <Download className="h-3.5 w-3.5" /> Download Report
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
