import React, { useState } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  StatusBar,
  ScrollView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { generateDailyReport } from '@/services/ai';
import { useSiteStore } from '@/stores/sites';
import { usePhotoStore } from '@/stores/photos';
import { COLORS } from '@/constants/theme';

interface ReportEntry {
  id: string;
  date: string;
  content: string;
  photoCount: number;
  violationCount: number;
}

export default function ReportsScreen() {
  const { activeSiteId, sites } = useSiteStore();
  const { photos } = usePhotoStore();
  const [generating, setGenerating] = useState(false);
  const [reports, setReports] = useState<ReportEntry[]>([]);
  const [selectedReport, setSelectedReport] = useState<ReportEntry | null>(null);
  const [sharing, setSharing] = useState(false);

  const activeSite = sites.find((s) => s.id === activeSiteId);
  const sitePhotos = photos.filter((p) => p.siteId === activeSiteId);

  const todayStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Photos taken today with analysis
  const todayPhotos = sitePhotos.filter((p) => {
    const pDate = new Date(p.createdAt);
    const today = new Date();
    return (
      pDate.getDate() === today.getDate() &&
      pDate.getMonth() === today.getMonth() &&
      pDate.getFullYear() === today.getFullYear() &&
      p.analysis !== undefined
    );
  });

  async function handleGenerateReport() {
    if (!activeSiteId || !activeSite) {
      Alert.alert('No Active Site', 'Please select an active site first.');
      return;
    }
    if (todayPhotos.length === 0) {
      Alert.alert(
        'No Photos Today',
        'Capture and analyze some photos today before generating a report.'
      );
      return;
    }

    setGenerating(true);
    try {
      const photoData = todayPhotos.map((p) => ({
        analysis: p.analysis!,
        location:
          p.latitude != null
            ? `${p.latitude.toFixed(4)}, ${p.longitude?.toFixed(4)}`
            : 'Unknown location',
        timestamp: new Date(p.createdAt).toLocaleTimeString(),
      }));

      const reportContent = await generateDailyReport(photoData, activeSite.name);

      const violationCount = todayPhotos.reduce(
        (sum, p) => sum + (p.analysis?.safetyViolations.length ?? 0),
        0
      );

      const newReport: ReportEntry = {
        id: `report_${Date.now()}`,
        date: new Date().toISOString(),
        content: reportContent,
        photoCount: todayPhotos.length,
        violationCount,
      };

      setReports((prev) => [newReport, ...prev]);
      setSelectedReport(newReport);
    } catch (err) {
      console.error('Report generation error:', err);
      Alert.alert('Generation Failed', 'Failed to generate report. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  async function handleShareReport(report: ReportEntry) {
    setSharing(true);
    try {
      const fileName = `SiteSync_Report_${new Date(report.date)
        .toISOString()
        .slice(0, 10)}.txt`;
      const fileUri = FileSystem.cacheDirectory + fileName;

      const reportText = `SITESYNC DAILY PROGRESS REPORT
Site: ${activeSite?.name ?? 'Unknown'}
Date: ${new Date(report.date).toLocaleDateString()}
Photos Analyzed: ${report.photoCount}
Safety Violations: ${report.violationCount}

${'='.repeat(50)}

${report.content}

${'='.repeat(50)}
Generated by SiteSync on ${new Date().toLocaleString()}`;

      await FileSystem.writeAsStringAsync(fileUri, reportText, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Daily Report',
        });
      } else {
        Alert.alert('Sharing not available', 'Sharing is not available on this device.');
      }
    } catch (err) {
      console.error('Share error:', err);
      Alert.alert('Share Failed', 'Failed to share report.');
    } finally {
      setSharing(false);
    }
  }

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor={COLORS.background} />

      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.headerTitle}>Reports</Text>
          <Text style={styles.headerSubtitle}>
            {activeSite?.name ?? 'No site selected'}
          </Text>
        </View>
      </View>

      <ScrollView
        style={styles.scrollView}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Generate Today's Report Card */}
        <View style={styles.generateCard}>
          <View style={styles.generateCardHeader}>
            <View style={styles.calendarIcon}>
              <Ionicons name="calendar" size={24} color={COLORS.primary} />
            </View>
            <View style={styles.generateCardInfo}>
              <Text style={styles.generateCardTitle}>Daily Progress Report</Text>
              <Text style={styles.generateCardDate}>{todayStr}</Text>
            </View>
          </View>

          {/* Stats row */}
          <View style={styles.statsRow}>
            <View style={styles.statItem}>
              <Text style={styles.statValue}>{todayPhotos.length}</Text>
              <Text style={styles.statLabel}>Photos Today</Text>
            </View>
            <View style={styles.statDivider} />
            <View style={styles.statItem}>
              <Text style={[styles.statValue, { color: sitePhotos.length > 0 ? COLORS.text : COLORS.textSecondary }]}>
                {sitePhotos.length}
              </Text>
              <Text style={styles.statLabel}>Total Photos</Text>
            </View>
            <View style={styles.statDivider} />
            <View style={styles.statItem}>
              <Text
                style={[
                  styles.statValue,
                  {
                    color:
                      todayPhotos.reduce(
                        (s, p) => s + (p.analysis?.safetyViolations.length ?? 0),
                        0
                      ) > 0
                        ? COLORS.error
                        : COLORS.text,
                  },
                ]}
              >
                {todayPhotos.reduce(
                  (s, p) => s + (p.analysis?.safetyViolations.length ?? 0),
                  0
                )}
              </Text>
              <Text style={styles.statLabel}>Violations</Text>
            </View>
          </View>

          <TouchableOpacity
            style={[
              styles.generateBtn,
              (generating || todayPhotos.length === 0) && styles.generateBtnDisabled,
            ]}
            onPress={handleGenerateReport}
            disabled={generating || todayPhotos.length === 0}
          >
            {generating ? (
              <>
                <ActivityIndicator size="small" color="#fff" />
                <Text style={styles.generateBtnText}>Generating with AI...</Text>
              </>
            ) : (
              <>
                <Ionicons name="sparkles" size={18} color="#fff" />
                <Text style={styles.generateBtnText}>Generate Today's Report</Text>
              </>
            )}
          </TouchableOpacity>

          {todayPhotos.length === 0 && (
            <Text style={styles.noPhotosHint}>
              Capture photos today to generate a report.
            </Text>
          )}
        </View>

        {/* Report History */}
        {reports.length > 0 && (
          <View style={styles.historySection}>
            <Text style={styles.historyTitle}>Report History</Text>
            {reports.map((report) => (
              <TouchableOpacity
                key={report.id}
                style={[
                  styles.reportCard,
                  selectedReport?.id === report.id && styles.reportCardSelected,
                ]}
                onPress={() =>
                  setSelectedReport(
                    selectedReport?.id === report.id ? null : report
                  )
                }
                activeOpacity={0.8}
              >
                <View style={styles.reportCardHeader}>
                  <View style={styles.reportCardLeft}>
                    <Ionicons
                      name="document-text"
                      size={18}
                      color={COLORS.primary}
                    />
                    <View>
                      <Text style={styles.reportCardDate}>
                        {new Date(report.date).toLocaleDateString('en-US', {
                          weekday: 'short',
                          month: 'short',
                          day: 'numeric',
                        })}
                      </Text>
                      <Text style={styles.reportCardMeta}>
                        {report.photoCount} photos ·{' '}
                        {report.violationCount > 0 ? (
                          <Text style={{ color: COLORS.error }}>
                            {report.violationCount} violations
                          </Text>
                        ) : (
                          'No violations'
                        )}
                      </Text>
                    </View>
                  </View>
                  <View style={styles.reportCardActions}>
                    <TouchableOpacity
                      style={styles.shareBtn}
                      onPress={() => handleShareReport(report)}
                      disabled={sharing}
                    >
                      {sharing ? (
                        <ActivityIndicator size="small" color={COLORS.primary} />
                      ) : (
                        <Ionicons
                          name="share-outline"
                          size={18}
                          color={COLORS.primary}
                        />
                      )}
                    </TouchableOpacity>
                    <Ionicons
                      name={
                        selectedReport?.id === report.id
                          ? 'chevron-up'
                          : 'chevron-down'
                      }
                      size={18}
                      color={COLORS.textSecondary}
                    />
                  </View>
                </View>

                {selectedReport?.id === report.id && (
                  <View style={styles.reportContent}>
                    <View style={styles.reportContentDivider} />
                    <Text style={styles.reportText}>{report.content}</Text>
                    <TouchableOpacity
                      style={styles.shareFullBtn}
                      onPress={() => handleShareReport(report)}
                      disabled={sharing}
                    >
                      <Ionicons name="share-social-outline" size={16} color="#fff" />
                      <Text style={styles.shareFullBtnText}>Share Report</Text>
                    </TouchableOpacity>
                  </View>
                )}
              </TouchableOpacity>
            ))}
          </View>
        )}

        {reports.length === 0 && !generating && (
          <View style={styles.emptyState}>
            <Ionicons name="document-text-outline" size={56} color={COLORS.border} />
            <Text style={styles.emptyStateTitle}>No Reports Yet</Text>
            <Text style={styles.emptyStateText}>
              Generate your first daily report to track and share site progress.
            </Text>
          </View>
        )}

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
  },
  header: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
  },
  headerSubtitle: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  generateCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 16,
  },
  generateCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  calendarIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  generateCardInfo: {
    flex: 1,
  },
  generateCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  generateCardDate: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.background,
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
    alignItems: 'center',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text,
  },
  statLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  statDivider: {
    width: 1,
    height: 32,
    backgroundColor: COLORS.border,
  },
  generateBtn: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
  },
  generateBtnDisabled: {
    backgroundColor: COLORS.textSecondary,
  },
  generateBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  noPhotosHint: {
    textAlign: 'center',
    color: COLORS.textSecondary,
    fontSize: 12,
    marginTop: 8,
  },
  historySection: {
    gap: 10,
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 4,
  },
  reportCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  reportCardSelected: {
    borderColor: COLORS.primary,
  },
  reportCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reportCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  reportCardDate: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
  },
  reportCardMeta: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  reportCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  shareBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reportContent: {
    marginTop: 4,
  },
  reportContentDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 12,
  },
  reportText: {
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 22,
    marginBottom: 14,
  },
  shareFullBtn: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
  },
  shareFullBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    gap: 10,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  emptyStateText: {
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 280,
  },
  bottomSpacer: {
    height: 24,
  },
});
