import { useEffect, useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { getBillById } from '../../lib/actions/bills';
import { createDisputeWithLetter } from '../../lib/actions/disputes';
import type { Bill } from '../../types';

export default function NewDisputeScreen() {
  const { billId } = useLocalSearchParams<{ billId: string }>();
  const [bill, setBill] = useState<Bill | null>(null);
  const [letter, setLetter] = useState('');
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!billId) { setLoading(false); return; }
    getBillById(billId)
      .then((b) => {
        setBill(b);
        if (b.ai_dispute_letter) setLetter(b.ai_dispute_letter);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [billId]);

  const handleSubmit = async () => {
    if (!bill || !letter.trim()) {
      Alert.alert('Please review the dispute letter before submitting.');
      return;
    }
    setSubmitting(true);
    try {
      const dispute = await createDisputeWithLetter(bill.id, letter);
      router.replace({ pathname: '/disputes/[id]', params: { id: dispute.id } });
    } catch (error: any) {
      Alert.alert('Error', error.message);
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loading}><ActivityIndicator size="large" color="#16a34a" /></View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Text style={styles.backBtnText}>✕</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>New Dispute</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {bill && (
          <View style={styles.billSummary}>
            <Text style={styles.billProvider}>{bill.provider_name || 'Unknown Provider'}</Text>
            <Text style={styles.billAmount}>
              Disputing: ${(bill.total_amount - (bill.fair_total || 0)).toFixed(2)} in overcharges
            </Text>
          </View>
        )}

        <View style={styles.letterSection}>
          <Text style={styles.sectionTitle}>Dispute Letter</Text>
          <Text style={styles.sectionSub}>
            This letter was generated by AI based on your bill analysis. Review and edit as needed.
          </Text>
          <TextInput
            style={styles.letterInput}
            value={letter}
            onChangeText={setLetter}
            multiline
            textAlignVertical="top"
            placeholder="Dispute letter will appear here after bill analysis..."
            placeholderTextColor="#94a3b8"
          />
        </View>

        <TouchableOpacity
          style={[styles.submitBtn, submitting && styles.submitBtnDisabled]}
          onPress={handleSubmit}
          disabled={submitting}
        >
          {submitting ? (
            <ActivityIndicator color="#ffffff" />
          ) : (
            <Text style={styles.submitBtnText}>Submit Dispute</Text>
          )}
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0fdf4' },
  loading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#16a34a',
  },
  backBtn: { padding: 4, width: 40 },
  backBtnText: { fontSize: 20, color: '#ffffff' },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#ffffff' },
  content: { flex: 1, padding: 16 },
  billSummary: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  billProvider: { fontSize: 16, fontWeight: '700', color: '#1e293b' },
  billAmount: { fontSize: 14, color: '#16a34a', marginTop: 4, fontWeight: '500' },
  letterSection: { marginBottom: 24 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1e293b', marginBottom: 4 },
  sectionSub: { fontSize: 13, color: '#64748b', marginBottom: 12, lineHeight: 20 },
  letterInput: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    fontSize: 14,
    color: '#1e293b',
    borderWidth: 1,
    borderColor: '#d1fae5',
    minHeight: 320,
    lineHeight: 22,
  },
  submitBtn: {
    backgroundColor: '#16a34a',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 32,
  },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: '#ffffff', fontWeight: '700', fontSize: 16 },
});
