import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  Modal,
  ActivityIndicator,
  Alert,
  Platform,
} from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Ionicons } from '@expo/vector-icons';
import { format } from 'date-fns';
import { useInspectionStore, type Inspection } from '@/stores/inspections';
import {
  generateInspectionReport,
  getScoreColor,
  type DamageAssessment,
} from '@/services/ai';
import { saveReport } from '@/services/supabase';
import {
  COLORS,
  STATUS_COLORS,
  SEVERITY_COLORS,
  SPACING,
  RADIUS,
} from '@/constants/theme';

// ---- Report HTML Template ----

function buildReportHtml(
  inspection: Inspection,
  reportText: string,
  generatedAt: string
): string {
  const scoreColor = getScoreColor(inspection.overallScore ?? 50);
  const photoRows = inspection.photos
    .filter((p) => p.assessment)
    .map((p) => {
      const a = p.assessment as DamageAssessment;
      const sev = SEVERITY_COLORS[a.severity];
      return `
        <tr>
          <td>${p.area}</td>
          <td style="color:${sev.text};background:${sev.bg};padding:2px 8px;border-radius:4px;font-weight:600">${a.severity.replace('_', ' ').toUpperCase()}</td>
          <td>${a.damageType}</td>
          <td>$${a.estimatedRepairCost.min.toLocaleString()} – $${a.estimatedRepairCost.max.toLocaleString()}</td>
          <td>${a.conditionScore}/100</td>
        </tr>`;
    })
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Property Damage Inspection Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, Arial, sans-serif; color: #1E293B; background: #fff; padding: 32px; }
    .header { background: #1E40AF; color: white; padding: 24px; border-radius: 8px; margin-bottom: 24px; }
    .header h1 { font-size: 22px; font-weight: 800; }
    .header p { opacity: 0.8; font-size: 13px; margin-top: 4px; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
    .meta-card { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 16px; }
    .meta-label { font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px; }
    .meta-value { font-size: 16px; font-weight: 700; color: #1E293B; margin-top: 4px; }
    .score-badge { font-size: 28px; font-weight: 800; color: ${scoreColor}; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
    th { background: #F1F5F9; padding: 10px 12px; text-align: left; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: #64748B; }
    td { padding: 10px 12px; border-bottom: 1px solid #E2E8F0; }
    .report-body { white-space: pre-wrap; font-size: 14px; line-height: 1.8; color: #334155; background: #F8FAFC; padding: 20px; border-radius: 8px; border: 1px solid #E2E8F0; }
    .section-title { font-size: 16px; font-weight: 700; color: #1E40AF; margin: 24px 0 8px; border-bottom: 2px solid #DBEAFE; padding-bottom: 6px; }
    .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Property Damage Inspection Report</h1>
    <p>Generated by InspectorAI &bull; ${generatedAt}</p>
  </div>

  <div class="meta-grid">
    <div class="meta-card">
      <div class="meta-label">Property Address</div>
      <div class="meta-value">${inspection.propertyAddress}</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Claim Number</div>
      <div class="meta-value">${inspection.claimNumber}</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Insured Name</div>
      <div class="meta-value">${inspection.insuredName}</div>
    </div>
    <div class="meta-card">
      <div class="meta-label">Overall Condition Score</div>
      <div class="score-badge">${inspection.overallScore ?? 'N/A'}<span style="font-size:14px;color:#64748B">/100</span></div>
    </div>
  </div>

  ${
    photoRows
      ? `<div class="section-title">Damage Summary by Area</div>
  <table>
    <thead><tr><th>Area</th><th>Severity</th><th>Damage Type</th><th>Est. Cost</th><th>Score</th></tr></thead>
    <tbody>${photoRows}</tbody>
  </table>`
      : ''
  }

  <div class="section-title">Full Inspection Report</div>
  <div class="report-body">${reportText}</div>

  <div class="footer">
    InspectorAI &bull; Property Damage Inspection Report &bull; ${generatedAt}<br/>
    This report is generated by AI assistance and should be reviewed by a licensed adjuster.
  </div>
</body>
</html>`;
}

// ---- Inspection Report Card ----

function ReportCard({
  inspection,
  onGenerate,
  generating,
}: {
  inspection: Inspection;
  onGenerate: (inspection: Inspection) => void;
  generating: boolean;
}) {
  const statusColors = STATUS_COLORS[inspection.status] ?? STATUS_COLORS.review;
  const score = inspection.overallScore;
  const scoreColor = score !== undefined ? getScoreColor(score) : COLORS.textSecondary;
  const photoCount = inspection.photos.filter((p) => p.assessment).length;

  return (
    <View style={styles.reportCard}>
      <View style={styles.cardTop}>
        <View style={{ flex: 1, marginRight: SPACING.sm }}>
          <Text style={styles.cardAddress} numberOfLines={2}>{inspection.propertyAddress}</Text>
          <Text style={styles.cardClaim}>Claim #{inspection.claimNumber}</Text>
          <Text style={styles.cardInsured}>{inspection.insuredName}</Text>
        </View>
        {score !== undefined && (
          <View style={[styles.scoreRing, { borderColor: scoreColor }]}>
            <Text style={[styles.scoreRingText, { color: scoreColor }]}>{score}</Text>
          </View>
        )}
      </View>

      <View style={styles.cardMeta}>
        <View style={[styles.statusBadge, { backgroundColor: statusColors.bg }]}>
          <Text style={[styles.statusText, { color: statusColors.text }]}>
            {inspection.status.replace('_', ' ').toUpperCase()}
          </Text>
        </View>
        <Text style={styles.metaText}>{photoCount} assessed photos</Text>
        <Text style={styles.metaText}>
          {format(new Date(inspection.createdAt), 'MMM d, yyyy')}
        </Text>
      </View>

      <TouchableOpacity
        style={[styles.generateBtn, generating && styles.generateBtnDisabled]}
        onPress={() => onGenerate(inspection)}
        disabled={generating}
      >
        {generating ? (
          <ActivityIndicator size="small" color="#fff" />
        ) : (
          <>
            <Ionicons name="sparkles-outline" size={16} color="#fff" />
            <Text style={styles.generateBtnText}>
              {inspection.reportHtml ? 'Regenerate Report' : 'Generate Report'}
            </Text>
          </>
        )}
      </TouchableOpacity>
    </View>
  );
}

// ---- Report Preview Modal ----

function ReportPreviewModal({
  inspection,
  reportHtml,
  onClose,
}: {
  inspection: Inspection | null;
  reportHtml: string;
  onClose: () => void;
}) {
  const [printing, setPrinting] = useState(false);
  const [sharing, setSharing] = useState(false);

  const handlePrint = useCallback(async () => {
    if (!inspection) return;
    setPrinting(true);
    try {
      await Print.printAsync({ html: reportHtml });
    } catch (err) {
      Alert.alert('Print Error', 'Could not print the report.');
    } finally {
      setPrinting(false);
    }
  }, [reportHtml, inspection]);

  const handleShare = useCallback(async () => {
    if (!inspection) return;
    setSharing(true);
    try {
      const { uri } = await Print.printToFileAsync({ html: reportHtml });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `Inspection Report - ${inspection.claimNumber}`,
        });
      } else {
        Alert.alert('Sharing Unavailable', 'File sharing is not available on this device.');
      }
    } catch (err) {
      Alert.alert('Share Error', 'Could not share the report.');
    } finally {
      setSharing(false);
    }
  }, [reportHtml, inspection]);

  if (!inspection) return null;

  return (
    <Modal
      visible={!!inspection}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <SafeAreaView style={styles.modalSafe}>
        {/* Modal Header */}
        <View style={styles.modalHeader}>
          <View style={{ flex: 1 }}>
            <Text style={styles.modalTitle}>Inspection Report</Text>
            <Text style={styles.modalSub}>Claim #{inspection.claimNumber}</Text>
          </View>
          <TouchableOpacity onPress={onClose} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
            <Ionicons name="close-circle" size={28} color={COLORS.textSecondary} />
          </TouchableOpacity>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionBar}>
          <TouchableOpacity
            style={[styles.actionBtn, styles.printBtn, printing && { opacity: 0.6 }]}
            onPress={handlePrint}
            disabled={printing}
          >
            {printing ? (
              <ActivityIndicator size="small" color={COLORS.primary} />
            ) : (
              <>
                <Ionicons name="print-outline" size={18} color={COLORS.primary} />
                <Text style={styles.printBtnText}>Print PDF</Text>
              </>
            )}
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.actionBtn, styles.shareBtn, sharing && { opacity: 0.6 }]}
            onPress={handleShare}
            disabled={sharing}
          >
            {sharing ? (
              <ActivityIndicator size="small" color="#fff" />
            ) : (
              <>
                <Ionicons name="share-outline" size={18} color="#fff" />
                <Text style={styles.shareBtnText}>Share PDF</Text>
              </>
            )}
          </TouchableOpacity>
        </View>

        {/* Report Text Preview */}
        <ScrollView contentContainerStyle={styles.previewContent}>
          <View style={styles.previewHeader}>
            <Text style={styles.previewTitle}>{inspection.propertyAddress}</Text>
            <Text style={styles.previewMeta}>
              {inspection.insuredName} &bull; Claim #{inspection.claimNumber}
            </Text>
            {inspection.overallScore !== undefined && (
              <View style={styles.previewScore}>
                <Text style={styles.previewScoreLabel}>Overall Condition Score</Text>
                <Text style={[styles.previewScoreValue, { color: getScoreColor(inspection.overallScore) }]}>
                  {inspection.overallScore}/100
                </Text>
              </View>
            )}
          </View>

          <View style={styles.reportTextBox}>
            <Text style={styles.reportText}>{inspection.reportHtml?.replace(/<[^>]*>/g, '') ?? ''}</Text>
          </View>
        </ScrollView>
      </SafeAreaView>
    </Modal>
  );
}

// ---- Main Screen ----

export default function ReportsScreen() {
  const { inspections, updateInspection } = useInspectionStore();
  const [generatingId, setGeneratingId] = useState<string | null>(null);
  const [previewInspection, setPreviewInspection] = useState<Inspection | null>(null);

  // Show inspections that are ready for reporting
  const reportableInspections = inspections.filter(
    (i) => i.status === 'review' || i.status === 'submitted'
  );

  const handleGenerateReport = useCallback(
    async (inspection: Inspection) => {
      setGeneratingId(inspection.id);
      try {
        const assessments = inspection.photos
          .filter((p) => p.assessment)
          .map((p) => ({ area: p.area, assessment: p.assessment! }));

        const overallScore = inspection.overallScore ?? 50;
        const reportText = await generateInspectionReport(
          inspection.propertyAddress,
          inspection.claimNumber,
          format(new Date(inspection.createdAt), 'MMMM d, yyyy'),
          assessments,
          overallScore
        );

        const generatedAt = format(new Date(), 'MMMM d, yyyy h:mm a');
        const reportHtml = buildReportHtml(inspection, reportText, generatedAt);

        updateInspection(inspection.id, { reportHtml, status: 'review' });

        // Try to save to Supabase (non-blocking)
        saveReport({ inspection_id: inspection.id, report_html: reportHtml }).catch(() => null);

        // Open preview with updated inspection data
        setPreviewInspection({ ...inspection, reportHtml });
      } catch (err) {
        Alert.alert('Report Generation Failed', 'Could not generate the report. Please check your API key and try again.');
      } finally {
        setGeneratingId(null);
      }
    },
    [updateInspection]
  );

  const handleOpenReport = useCallback((inspection: Inspection) => {
    if (inspection.reportHtml) {
      setPreviewInspection(inspection);
    } else {
      handleGenerateReport(inspection);
    }
  }, [handleGenerateReport]);

  return (
    <SafeAreaView style={styles.safe}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Reports</Text>
        <Text style={styles.headerSub}>
          {reportableInspections.length} inspection{reportableInspections.length !== 1 ? 's' : ''} ready
        </Text>
      </View>

      {/* List */}
      <FlatList
        data={reportableInspections}
        keyExtractor={(item) => item.id}
        contentContainerStyle={[
          styles.listContent,
          reportableInspections.length === 0 && styles.emptyContainer,
        ]}
        ListEmptyComponent={
          <View style={styles.emptyState}>
            <Ionicons name="document-text-outline" size={64} color={COLORS.border} />
            <Text style={styles.emptyTitle}>No Reports Yet</Text>
            <Text style={styles.emptyText}>
              Complete an inspection and mark it for review to generate a PDF report here.
            </Text>
          </View>
        }
        renderItem={({ item }) => (
          <View>
            <ReportCard
              inspection={item}
              onGenerate={handleGenerateReport}
              generating={generatingId === item.id}
            />
            {item.reportHtml && (
              <TouchableOpacity
                style={styles.viewReportBtn}
                onPress={() => handleOpenReport(item)}
              >
                <Ionicons name="eye-outline" size={16} color={COLORS.primary} />
                <Text style={styles.viewReportText}>View Report</Text>
              </TouchableOpacity>
            )}
          </View>
        )}
        ItemSeparatorComponent={() => <View style={{ height: SPACING.sm }} />}
      />

      {/* Preview Modal */}
      <ReportPreviewModal
        inspection={previewInspection}
        reportHtml={previewInspection?.reportHtml ?? ''}
        onClose={() => setPreviewInspection(null)}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  header: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.md,
    paddingTop: Platform.OS === 'android' ? SPACING.md : 4,
    paddingBottom: SPACING.md,
  },
  headerTitle: { fontSize: 22, fontWeight: '800', color: '#fff' },
  headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
  listContent: { padding: SPACING.md, paddingBottom: 100 },
  emptyContainer: { flexGrow: 1 },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.xl,
    marginTop: SPACING.xl,
  },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: COLORS.text, marginTop: SPACING.md },
  emptyText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: SPACING.sm,
    lineHeight: 20,
  },
  reportCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTop: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.sm },
  cardAddress: { fontSize: 15, fontWeight: '700', color: COLORS.text },
  cardClaim: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  cardInsured: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  scoreRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreRingText: { fontSize: 14, fontWeight: '800' },
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
    flexWrap: 'wrap',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
  },
  statusText: { fontSize: 10, fontWeight: '700' },
  metaText: { fontSize: 12, color: COLORS.textSecondary },
  generateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm + 2,
  },
  generateBtnDisabled: { opacity: 0.6 },
  generateBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  viewReportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm,
    marginTop: SPACING.xs,
    backgroundColor: COLORS.surface,
  },
  viewReportText: { color: COLORS.primary, fontSize: 14, fontWeight: '600' },
  // Modal
  modalSafe: { flex: 1, backgroundColor: COLORS.background },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text },
  modalSub: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  actionBar: {
    flexDirection: 'row',
    gap: SPACING.sm,
    padding: SPACING.md,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm + 2,
  },
  printBtn: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.surface,
  },
  printBtnText: { color: COLORS.primary, fontSize: 14, fontWeight: '700' },
  shareBtn: { backgroundColor: COLORS.primary },
  shareBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  previewContent: { padding: SPACING.md, paddingBottom: 60 },
  previewHeader: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  previewTitle: { fontSize: 16, fontWeight: '800', color: '#fff' },
  previewMeta: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 4 },
  previewScore: { marginTop: SPACING.sm },
  previewScoreLabel: { fontSize: 11, color: 'rgba(255,255,255,0.7)', fontWeight: '600' },
  previewScoreValue: { fontSize: 24, fontWeight: '800', marginTop: 2 },
  reportTextBox: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  reportText: {
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 24,
  },
});
