import type { Program } from '@/services/eligibility';

export const FEDERAL_PROGRAMS: Program[] = [
  {
    id: '1', code: 'SNAP', name: 'SNAP (Food Stamps)', nameEs: 'SNAP (Cupones de comida)',
    category: 'food',
    description: 'Monthly food benefits for groceries',
    descriptionEs: 'Beneficios mensuales de alimentos para comestibles',
    estimatedAnnualMin: 1800, estimatedAnnualMax: 5000,
    applicationUrl: 'https://www.fns.usda.gov/snap/apply',
  },
  {
    id: '2', code: 'MEDICAID', name: 'Medicaid', nameEs: 'Medicaid',
    category: 'healthcare',
    description: 'Free or low-cost health coverage',
    descriptionEs: 'Cobertura médica gratis o de bajo costo',
    estimatedAnnualMin: 3000, estimatedAnnualMax: 8000,
    applicationUrl: 'https://www.healthcare.gov/medicaid-chip/',
  },
  {
    id: '3', code: 'EITC', name: 'Earned Income Tax Credit', nameEs: 'Crédito Tributario por Ingreso del Trabajo',
    category: 'tax_credit',
    description: 'Tax refund for working individuals',
    descriptionEs: 'Reembolso de impuestos para trabajadores',
    estimatedAnnualMin: 600, estimatedAnnualMax: 7830,
    applicationUrl: 'https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit',
  },
  {
    id: '4', code: 'WIC', name: 'WIC (Women, Infants, Children)', nameEs: 'WIC',
    category: 'food',
    description: 'Nutrition benefits for mothers and young children',
    descriptionEs: 'Beneficios nutricionales para madres y niños pequeños',
    estimatedAnnualMin: 500, estimatedAnnualMax: 800,
    applicationUrl: 'https://www.fns.usda.gov/wic',
  },
  {
    id: '5', code: 'CHIP', name: "Children's Health Insurance", nameEs: 'Seguro Médico para Niños',
    category: 'healthcare',
    description: "Health coverage for children who don't qualify for Medicaid",
    descriptionEs: 'Cobertura médica para niños que no califican para Medicaid',
    estimatedAnnualMin: 1200, estimatedAnnualMax: 4000,
    applicationUrl: 'https://www.healthcare.gov/medicaid-chip/childrens-health-insurance-program/',
  },
  {
    id: '6', code: 'LIHEAP', name: 'LIHEAP (Energy Assistance)', nameEs: 'Asistencia con Energía',
    category: 'housing',
    description: 'Help paying heating and cooling bills',
    descriptionEs: 'Ayuda para pagar facturas de calefacción y enfriamiento',
    estimatedAnnualMin: 400, estimatedAnnualMax: 1500,
    applicationUrl: 'https://www.acf.hhs.gov/ocs/low-income-home-energy-assistance-program-liheap',
  },
  {
    id: '7', code: 'SSI', name: 'Supplemental Security Income', nameEs: 'Seguridad de Ingreso Suplementario',
    category: 'cash',
    description: 'Monthly payments for disabled and elderly',
    descriptionEs: 'Pagos mensuales para discapacitados y ancianos',
    estimatedAnnualMin: 6000, estimatedAnnualMax: 10000,
    applicationUrl: 'https://www.ssa.gov/ssi/',
  },
  {
    id: '8', code: 'TANF', name: 'TANF (Cash Assistance)', nameEs: 'Asistencia en Efectivo',
    category: 'cash',
    description: 'Temporary cash assistance for families',
    descriptionEs: 'Asistencia temporal en efectivo para familias',
    estimatedAnnualMin: 2400, estimatedAnnualMax: 6000,
    applicationUrl: 'https://www.acf.hhs.gov/ofa/programs/tanf',
  },
  {
    id: '9', code: 'HEAD_START', name: 'Head Start (Early Education)', nameEs: 'Head Start (Educación Temprana)',
    category: 'childcare',
    description: 'Free early education for young children',
    descriptionEs: 'Educación temprana gratuita para niños pequeños',
    estimatedAnnualMin: 8000, estimatedAnnualMax: 12000,
    applicationUrl: 'https://www.acf.hhs.gov/ohs',
  },
  {
    id: '10', code: 'ACP', name: 'Affordable Connectivity Program', nameEs: 'Programa de Conectividad Asequible',
    category: 'cash',
    description: '$30/month discount on internet bills',
    descriptionEs: 'Descuento de $30/mes en facturas de internet',
    estimatedAnnualMin: 360, estimatedAnnualMax: 360,
    applicationUrl: 'https://www.affordableconnectivity.gov/',
  },
];
